name: mobile
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0
  just_audio: ^0.9.36
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  provider: ^6.1.5+1
  path_provider: ^2.1.1
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_launcher_name: ^0.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/image.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/images/logo.png

flutter_launcher_name:
  name: Voicera
